### PR TITLE
fix: promoting moves are animated

### LINKED ISSUE #220: [BUG] Promoting moves are not animated
**Describe the bug**
Promoting moves are not animated even when `animationDurationInMs` option is set. All moves are animated except for promotions, which appear instant.

`utils.getPositionUpdates` only considers animating pieces of the same type so it always misses promoting from P to Q, R, B, N.

**To Reproduce**

1. set animationDurationInMs to a positive value
2. render position right before a promotion
3. render position right after a promotion

You can also see this behavior if you let the random engine promote a pawn in Storybook > Options API > animationDurationInMs 

**Expected behaviour**

The position update should have the pawn animate to the promoting square where it turns into the promoted piece

**Screen Recording or Screenshots**

Current Behavior:

https://github.com/user-attachments/assets/513427c2-1a46-41bc-82cc-39f87c2a93e7

Ideal Behavior:

https://github.com/user-attachments/assets/2daa519a-6c8d-4ade-a821-a233ef9ade76

**Environment (please complete the following information):**

- Package version: v5.4.0 
- React version v19.1.1
- Node version v24.9.0

**Desktop (please complete the following information):**

- OS: macOS
- Browser: Chrome
- Version: 141.0.7390.123

**Smartphone (please complete the following information):**

N/A

**Additional context**

### PR DESCRIPTION
**Pull request by antonryoung02**
## Description

I added `utils.getPromotionUpdates` and `utils.pawnPromotesAtSquares` to identify promoting moves.

In the animation useEffect I added a condition where the promotion is animated only if `positionUpdates` doesn't have any pieces to animate and `promotionUpdates` has one piece to animate. I added these constraints to simplify the problem, because the main benefit of the fix is to animate when only the promotion move is being played or undone. In other cases it can be hard to verify if the promotion actually happened or how you should handle conflicts with `positionUpdates`.

Fixes #220 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

- [x] Verified the animation happens when the engine promotes in Storybook > Options API > animationDurationInMs

I didn't write any unit tests for my logic because I didn't see a test suite to add them to. Let me know if I'm misunderstanding storybook!

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

## Additional context

Add any other context about the pull request here.

### CODE REVIEW

File: src/utils.ts [hunk 1]
```diff
@@ -269,6 +269,119 @@ export function getPositionUpdates(
...
+    return false;
+  }
+
+  const columnDifference = Math.abs(
+    chessColumnToColumnIndex(pawnSquare[0], noOfColumns, 'black') -
+      chessColumnToColumnIndex(promotionSquare[0], noOfColumns, 'black'),
+  );
+  if (columnDifference > 1 || oldPiece[0] !== newPiece[0]) {
+    return false;
+  }
```
Comment (Clariity) [inline src/utils.ts]: can you comment what this line does please? wasn't immediately obvious that `oldPiece[0] !== newPiece[0]` meant it was checking if the piece colours were different

File: src/utils.ts [hunk 2]
```diff
@@ -269,6 +269,119 @@ export function getPositionUpdates(
...
+    promotionSquare = oldSquare;
+  } else {
+    return false;
+  }
+
+  const columnDifference = Math.abs(
+    chessColumnToColumnIndex(pawnSquare[0], noOfColumns, 'black') -
+      chessColumnToColumnIndex(promotionSquare[0], noOfColumns, 'black'),
+  );
+  if (columnDifference > 1 || oldPiece[0] !== newPiece[0]) {
```
Comment (Clariity) [inline src/utils.ts]:
```suggestion

  // ensure piece has moved at most 1 column away and is the same colour
  if (columnDifference > 1 || oldPiece[0] !== newPiece[0]) {
```
